#pragma once
#include "pch.hpp"
#include "core/api.hpp"

namespace ATMA
{

	enum class ATMA_API KeyEnum
    {
#ifdef _WINDOWS
        NUMPAD_ADD          = 0x6B,
        BACKSPACE	        = 0x08,
        BREAK	            = 0x03,
        CLEAR	            = 0x0C,
        NUMPAD_DECIMAL	    = 0x6E,
        NUMPAD_DIVIDE	    = 0x6F,
        ESCAPE	            = 0x1B,
        _0	                = 0x30,
        _1	                = 0x31,
        _2	                = 0x32,
        _3	                = 0x33,
        _4	                = 0x34,
        _5	                = 0x35,
        _6	                = 0x36,
        _7	                = 0x37,
        _8	                = 0x38,
        _9	                = 0x39,
        _A	                = 0x41,
        _B	                = 0x42,
        _C	                = 0x43,
        _D	                = 0x44,
        _E	                = 0x45,
        _F	                = 0x46,
        _G	                = 0x47,
        _H	                = 0x48,
        _I	                = 0x49,
        _J	                = 0x4A,
        _K	                = 0x4B,
        _L	                = 0x4C,
        _M	                = 0x4D,
        _N	                = 0x4E,
        _O	                = 0x4F,
        _P	                = 0x50,
        _Q	                = 0x51,
        _R	                = 0x52,
        _S	                = 0x53,
        _T	                = 0x54,
        _U	                = 0x55,
        _V	                = 0x56,
        _W	                = 0x57,
        _X	                = 0x58,
        _Y	                = 0x59,
        _Z	                = 0x5A,
        GRAVE               = 0xC0,
        LEFTBRACE           = 0xDB,
        RIGHTBRACE          = 0xDD,
        BACKSLASH           = 0xDC,
        SEMICOLON           = 0xBA,
        QUOTE               = 0xDE,
        COMMA               = 0xBC,
        PERIOD              = 0xBE,
        SLASH               = 0xBF,
        NUMPAD_MULTIPLY	    = 0x6A,
        NUMPAD0	            = 0x60,
        NUMPAD1	            = 0x61,
        NUMPAD2	            = 0x62,
        NUMPAD3	            = 0x63,
        NUMPAD4	            = 0x64,
        NUMPAD5	            = 0x65,
        NUMPAD6	            = 0x66,
        NUMPAD7	            = 0x67,
        NUMPAD8	            = 0x68,
        NUMPAD9	            = 0x69,
        RETURN	            = 0x0D,
        SELECT	            = 0x29,
        SPACE	            = 0x20,
        SUBTRACT	        = 0x6D,
        TAB	                = 0x09,
        CAPITAL         	= 0x14,
        _DELETE	            = 0x2E,
        DOWN	            = 0x28,
        END	                = 0x23,
        F1	                = 0x70,
        F10	                = 0x79,
        F11	                = 0x7A,
        F12	                = 0x7B,
        F13	                = 0x7C,
        F14	                = 0x7D,
        F15	                = 0x7E,
        F16	                = 0x7F,
        F17	                = 0x80,
        F18	                = 0x81,
        F19	                = 0x82,
        F2	                = 0x71,
        F20	                = 0x83,
        F21	                = 0x84,
        F22	                = 0x85,
        F23	                = 0x86,
        F24	                = 0x87,
        F3	                = 0x72,
        F4	                = 0x73,
        F5	                = 0x74,
        F6	                = 0x75,
        F7	                = 0x76,
        F8	                = 0x77,
        F9	                = 0x78,
        INSERT	            = 0x2D,
        LCONTROL	        = 0xA2,
        LALT                = 0xA4,
        LEFT	            = 0x25,
        LMENU	            = 0xA4,
        LSHIFT	            = 0xA0,
        LWIN	            = 0x5B,
        NUMLOCK	            = 0x90,
        PAUSE	            = 0x13,
        PRINT	            = 0x2A,
        RCONTROL	        = 0xA3,
        RALT                = 0xA5,
        RIGHT	            = 0x27,
        RMENU	            = 0xA5,
        RSHIFT	            = 0xA1,
        RWIN	            = 0x5C,
        UP	                = 0x26,
        PAGEUP              = 0x21,
        PAGEDOWN            = 0x22,
#elif __linux__
        NUMPAD_ADD          = XK_KP_Add,
        BACKSPACE	        = XK_BackSpace,
        BREAK	            = XK_Break,
        CLEAR	            = XK_Clear,
        NUMPAD_DECIMAL	    = XK_KP_Decimal,
        NUMPAD_DIVIDE	    = XK_KP_Divide,
        ESCAPE	            = XK_Escape,
        _0	                = XK_0,
        _2	                = XK_1,
        _1	                = XK_2,
        _3	                = XK_3,
        _4	                = XK_4,
        _5	                = XK_5,
        _6	                = XK_6,
        _7	                = XK_7,
        _8	                = XK_8,
        _9	                = XK_9,
        _A	                = XK_A,
        _B	                = XK_B,
        _C	                = XK_C,
        _D	                = XK_D,
        _E	                = XK_E,
        _F	                = XK_F,
        _G	                = XK_G,
        _H	                = XK_H,
        _I	                = XK_I,
        _J	                = XK_J,
        _K	                = XK_K,
        _L	                = XK_L,
        _M	                = XK_M,
        _N	                = XK_N,
        _O	                = XK_O,
        _P	                = XK_P,
        _Q	                = XK_Q,
        _R	                = XK_R,
        _S	                = XK_S,
        _T	                = XK_T,
        _U	                = XK_U,
        _V	                = XK_V,
        _W	                = XK_W,
        _X	                = XK_X,
        _Y	                = XK_Y,
        _Z	                = XK_Z,
        GRAVE               = XK_grave,
        LEFTBRACE           = XK_braceleft,
        RIGHTBRACE          = XK_braceright,
        BACKSLASH           = XK_backslash,
        SEMICOLON           = XK_semicolon,
        QUOTE               = XK_quotedbl,
        COMMA               = XK_comma,
        PERIOD              = XK_period,
        SLASH               = XK_slash,
        NUMPAD_MULTIPLY	    = XK_KP_Multiply,
        NUMPAD0	            = XK_KP_0,
        NUMPAD1	            = XK_KP_1,
        NUMPAD2	            = XK_KP_2,
        NUMPAD3	            = XK_KP_3,
        NUMPAD4	            = XK_KP_4,
        NUMPAD5	            = XK_KP_5,
        NUMPAD6	            = XK_KP_6,
        NUMPAD7	            = XK_KP_7,
        NUMPAD8	            = XK_KP_8,
        NUMPAD9	            = XK_KP_9,
        RETURN	            = XK_Return,
        SELECT	            = XK_Select,
        SEPARATOR	        = XK_KP_Separator,
        SPACE	            = XK_space,
        SUBTRACT	        = XK_hyphen,
        TAB	                = XK_Tab,
        CAPITAL         	= XK_Caps_Lock,
        _DELETE	            = XK_Delete,
        DOWN	            = XK_Down,
        END	                = XK_End,
        F1	                = XK_F1,
        F10	                = XK_F10,
        F11	                = XK_F11,
        F12	                = XK_F12,
        F13	                = XK_F13,
        F14	                = XK_F14,
        F15	                = XK_F15,
        F16	                = XK_F16,
        F17	                = XK_F17,
        F18	                = XK_F18,
        F19	                = XK_F19,
        F2	                = XK_F2,
        F20	                = XK_F20,
        F21	                = XK_F21,
        F22	                = XK_F22,
        F23	                = XK_F23,
        F24	                = XK_F24,
        F3	                = XK_F3,
        F4	                = XK_F4,
        F5	                = XK_F5,
        F6	                = XK_F6,
        F7	                = XK_F7,
        F8	                = XK_F8,
        F9	                = XK_F9,
        INSERT	            = XK_Insert,
        LCONTROL	        = XK_Control_L,
        LALT                = XK_Alt_L,
        LEFT	            = XK_Left,
        LMENU	            = XK_Menu,
        LSHIFT	            = XK_Shift_L,
        NUMLOCK	            = XK_Num_Lock,
        PAUSE	            = XK_Pause,
        PRINT	            = XK_Print,
        RCONTROL	        = XK_Control_R,
        RALT                = XK_Alt_R,
        RIGHT	            = XK_Right,
        RMENU	            = XK_Menu,
        RSHIFT	            = XK_Shift_R,
        UP	                = XK_Up,
        PAGEUP              = XK_Page_Up,
        PAGEDOWN            = XK_Page_Down,
#endif
    };

    class ATMA_API KeyCode
    {
    public:
        // constructor with name
        KeyCode(const KeyEnum &l_type): m_type(l_type) {}

        // conversion constructor
        KeyCode(const unsigned int &l_int): m_type(static_cast<KeyEnum>(l_int)) {}

        // conversion operator
        operator unsigned int()
        {
            return static_cast<unsigned int>(m_type);
        }
    private:
        const KeyEnum m_type;
    };

}