SET "CURRENTPATH=%cd%"
SET "PROJECTPATH=%~dp0.."
cd "%PROJECTPATH%"
SET "GTESTPATH=%PROJECTPATH%\out\build\lib\%1\"
SET "SPDLOGPATH=%PROJECTPATH%\out\build\_deps\spdlog-build\%1\"
SET "SFMLPATH=%PROJECTPATH%\out\build\_deps\sfml-build\lib\%1\"
SET "PATH=%GTESTPATH%;%SPDLOGPATH%;%SFMLPATH%;%PATH%"
"%PROJECTPATH%\out\build\bin\%1\Atomina_Test.exe"
cd "%CURRENTPATH%"