#include "render/GLTexture.hpp"
#include "util/ATConst.hpp"
#include <atomina.hpp>
#include <memory>

class RunState: public ATMA::BaseState
{
public:
    // default constructor
    RunState(ATMA::ATMAContext *l_ctx): BaseState(l_ctx)
    {
        m_obj = l_ctx->m_attrMan->createObject();
        m_backgroundObj = l_ctx->m_attrMan->createObject();
        m_vertID = l_ctx->m_resMan->registerResource("vertex", 1u, "shader/defaultVertex.shader");
        m_fragID = l_ctx->m_resMan->registerResource("frag", 1u, "shader/defaultFrag.shader");
        m_animID = l_ctx->m_resMan->registerResource("anim", 2u, "res/Ball.anim");
        m_textureID = l_ctx->m_resMan->registerResource("texture", 0u, "res/Ball.png");
        m_backgroundID = l_ctx->m_resMan->registerResource("pixel", 0u, "res/Pixels.png");
        m_vert = l_ctx->m_resMan->loadResource<ATMA::GLShader>(m_vertID);
        m_vert->compile(ATMA::ShaderType::Vertex);
        m_frag = l_ctx->m_resMan->loadResource<ATMA::GLShader>(m_fragID);
        m_frag->compile(ATMA::ShaderType::Fragment);
        m_anim = l_ctx->m_resMan->loadResource<ATMA::Animation>(m_animID);
        m_texture = l_ctx->m_resMan->loadResource<ATMA::GLTexture>(m_textureID);
        m_background = l_ctx->m_resMan->loadResource<ATMA::GLTexture>(m_backgroundID);
    }

    /**
     * function called by context when activating state
     */
    void activate(ATMA::ATMAContext *l_ctx) override
    {
        std::shared_ptr<ATMA::Animation> anim = std::make_shared<ATMA::Animation>(ATMA::AnimationData{
            "pixels",
            6,
            3,
            {1.f, 1.f},
            {0.f, 2.f},
            std::vector<ATMA::FrameData>{
              {4, std::bitset<ATConst::BITSET_SIZE>{}},
              {4, std::bitset<ATConst::BITSET_SIZE>{}},
              {4, std::bitset<ATConst::BITSET_SIZE>{}},
              {4, std::bitset<ATConst::BITSET_SIZE>{}},
              {4, std::bitset<ATConst::BITSET_SIZE>{}},
              {4, std::bitset<ATConst::BITSET_SIZE>{}}
            },
            true
        });
        m_prog = ATMA::GLProgram::makeProgram();
        m_prog->attachShader(m_vert);
        m_prog->attachShader(m_frag);
        m_prog->link();
        m_prog->exec();
        l_ctx->m_attrMan->addAttribute(l_ctx, m_obj, ATMA::AttributeType(ATMA::Attribute::Animation));
        l_ctx->m_attrMan->addAttribute(l_ctx, m_backgroundObj, ATMA::AttributeType(ATMA::Attribute::Animation));
        l_ctx->m_attrMan->addAttribute(l_ctx, m_obj, ATMA::AttributeType(ATMA::Attribute::Sprite));
        l_ctx->m_attrMan->addAttribute(l_ctx, m_backgroundObj, ATMA::AttributeType(ATMA::Attribute::Sprite));
        auto animAttr =
            l_ctx->m_attrMan->getAttribute<ATMA::AttrAnimation>(m_obj, ATMA::AttributeType(ATMA::Attribute::Animation));
        animAttr->m_self = m_anim;
        auto spriteAttr =
            l_ctx->m_attrMan->getAttribute<ATMA::AttrSprite>(m_obj, ATMA::AttributeType(ATMA::Attribute::Sprite));
        spriteAttr->m_self->m_texture = m_texture;
        spriteAttr->m_self->m_prog = m_prog;
        spriteAttr->m_self->m_size = ATMA::Vec2<float>{100.f, 100.f};
        spriteAttr->m_self->m_stackPos = 1;
        animAttr = l_ctx->m_attrMan->getAttribute<ATMA::AttrAnimation>(
            m_backgroundObj, ATMA::AttributeType(ATMA::Attribute::Animation)
        );
        animAttr->m_self = anim;
        spriteAttr = l_ctx->m_attrMan->getAttribute<ATMA::AttrSprite>(
            m_backgroundObj, ATMA::AttributeType(ATMA::Attribute::Sprite)
        );
        spriteAttr->m_self->m_texture = m_background;
        spriteAttr->m_self->m_prog = m_prog;
        spriteAttr->m_self->m_size = ATMA::Vec2<float>{100.f, 100.f};
        spriteAttr->m_self->m_stackPos = 0;
    }

    /**
     * function called by context when deactivating state
     */
    void deactivate(ATMA::ATMAContext *l_ctx) override
    {
        l_ctx->m_attrMan->clearObject(l_ctx, m_obj);
    }

    /**
     * gives the type id of the state
     * each state should give a different type id
     * @returns type id of the state
     */
    unsigned int getId() const override
    {
        return ATMA::StateType(ATMA::State::COUNT);
    }

    /**
     * passes window events to be handled by the state
     * @param l_ctx Engine Context
     * @param l_winEvent the event generated by the window
     * @returns whether or not the event was handled
     */
    void handleInput(ATMA::ATMAContext *l_ctx, const ATMA::WindowEvent &l_winEvent) override {}

    unsigned int m_obj;
    unsigned int m_backgroundObj;
    unsigned int m_animID;
    std::shared_ptr<ATMA::Animation> m_anim;
    unsigned int m_textureID;
    std::shared_ptr<ATMA::GLTexture> m_texture;
    unsigned int m_backgroundID;
    std::shared_ptr<ATMA::GLTexture> m_background;
    unsigned int m_vertID;
    std::shared_ptr<ATMA::GLShader> m_vert;
    unsigned int m_fragID;
    std::shared_ptr<ATMA::GLShader> m_frag;
    std::shared_ptr<ATMA::GLProgram> m_prog;
};
