name: Atomina

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .


  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.23.x'

    - name: Setup SFML Prerequisites
      run: sudo apt-get install -y g++ libgl1-mesa-dev libx11-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev libfreetype-dev libxrandr-dev libogg-dev libvorbisenc2 libvorbisfile3 libxcursor-dev libtbb-dev libbtbb-dev

    - name: Checkout action repo branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: 'recursive'
    - run: git checkout HEAD    
      
    - name: Build Modules
      working-directory: ${{env.SOLUTION_FILE_PATH}} 
      run: bash sbin/buildmodules.sh
      
    - name: Build Project
      working-directory: ${{env.SOLUTION_FILE_PATH}} 
      run: bash sbin/buildproject.sh -DIntel_Processor:BOOL=true

    - name: Run Tests
      working-directory: ${{env.SOLUTION_FILE_PATH}} 
      env:
        LD_LIBRARY_PATH: $HOME/work/project-atomina/project-atomina/ext/lib
      run: ls $HOME/work/project-atomina/project-atomina/ext/lib && echo $LD_LIBRARY_PATH && bash sbin/runtests.sh
      
