name: Atomina

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .


  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

  BUILD_PLATFORM: x64

jobs:
  build_linux:
    strategy:
      matrix:
       build_type: [Release, Debug]

    runs-on: ubuntu-20.04

    steps:
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.23.x'
    
    - name: pack update
      run: sudo apt-get update

    - name: Setup SFML Prerequisites
      run: sudo apt-get install -y --fix-missing g++ xorg-dev libgl1-mesa-dev libx11-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev libfreetype-dev libxrandr-dev libogg-dev libvorbisenc2 libvorbisfile3 libxcursor-dev libtbb-dev libbtbb-dev

    - name: Checkout action repo branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: 'recursive'
    - run: git checkout HEAD    
      
    - name: Build Project
      working-directory: ${{env.SOLUTION_FILE_PATH}} 
      run: bash sbin/buildproject.sh ${{matrix.build_type}} -DIntel_Processor:BOOL=true

    - name: Run Tests
      working-directory: ${{env.SOLUTION_FILE_PATH}} 
      run: ls out/build/bin && bash sbin/runtests.sh ${{matrix.build_type}}
  
  build_windows:
    strategy:
      matrix:
       build_type: [Release, Debug]

    runs-on: windows-2019

    steps:
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.23.x'

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.0

    - name: Checkout action repo branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: 'recursive'
    - run: git checkout HEAD    

    - name: Build Project
      working-directory: ${{env.SOLUTION_FILE_PATH}} 
      run: sbin/buildproject.bat ${{matrix.build_type}} -DIntel_Processor:BOOL=true

    - name: Run Tests
      working-directory: ${{env.SOLUTION_FILE_PATH}} 
      run: sbin/runtests.bat ${{matrix.build_type}}

